Attempt to fix: TypeError: CollectingListener.update_service() missing 1 required positional argument: 'state_change' by making the state_change argument optional. It is not used anyway